// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type GameVideoReq struct {
	GameId  int64 `form:"gameId"`
	SceneId int64 `form:"sceneId"`
}

type GameVideoResp struct {
	Id      int64             `json:"id"`
	Video   string            `json:"video"` // video url
	Title   string            `json:"title"`
	Brief   string            `json:"brief"`
	Options []GameVideoOption `json:"options"` // children node
}

type GameVideoOption struct {
	Id    int64  `json:"id"`
	Value string `json:"value"` // option text
	Audio string `json:"audio"` // audio url
	Video string `json:"video"` // video url
	Title string `json:"title"`
}
