// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.3

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	gSceneFieldNames          = builder.RawFieldNames(&GScene{})
	gSceneRows                = strings.Join(gSceneFieldNames, ",")
	gSceneRowsExpectAutoSet   = strings.Join(stringx.Remove(gSceneFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	gSceneRowsWithPlaceHolder = strings.Join(stringx.Remove(gSceneFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	gSceneModel interface {
		Insert(ctx context.Context, data *GScene) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*GScene, error)
		Update(ctx context.Context, data *GScene) error
		Delete(ctx context.Context, id int64) error
	}

	defaultGSceneModel struct {
		conn  sqlx.SqlConn
		table string
	}

	GScene struct {
		Id         int64     `db:"id"`          // 主键
		GameId     int64     `db:"game_id"`     // 游戏id
		ParentId   string    `db:"parent_id"`   // 父级id
		Label      string    `db:"label"`       // 选项名称
		LabelAudio string    `db:"label_audio"` // 标签音效
		Title      string    `db:"title"`       // 场景标题
		VideoUrl   string    `db:"video_url"`   // 视频url
		Brief      string    `db:"brief"`       // 简介
		Sort       int64     `db:"sort"`        // 排序 从大到小
		CreatedAt  time.Time `db:"created_at"`  // 创建时间
		UpdatedAt  time.Time `db:"updated_at"`  // 更新时间
	}
)

func newGSceneModel(conn sqlx.SqlConn) *defaultGSceneModel {
	return &defaultGSceneModel{
		conn:  conn,
		table: "`g_scene`",
	}
}

func (m *defaultGSceneModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultGSceneModel) FindOne(ctx context.Context, id int64) (*GScene, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gSceneRows, m.table)
	var resp GScene
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGSceneModel) Insert(ctx context.Context, data *GScene) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, gSceneRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.GameId, data.ParentId, data.Label, data.LabelAudio, data.Title, data.VideoUrl, data.Brief, data.Sort)
	return ret, err
}

func (m *defaultGSceneModel) Update(ctx context.Context, data *GScene) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, gSceneRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.GameId, data.ParentId, data.Label, data.LabelAudio, data.Title, data.VideoUrl, data.Brief, data.Sort, data.Id)
	return err
}

func (m *defaultGSceneModel) tableName() string {
	return m.table
}
