// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	v1game "video_game_api/internal/handler/v1/game"
	"video_game_api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/from/:name",
					Handler: v1game.Video_game_apiHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/video",
					Handler: v1game.VideoHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1/game"),
	)
}
